[build]
  command = "CI=false npm install && npm run build"
  publish = "front/build" 
  functions = "back/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
