[build]
  publish = "build"
  command = "npm run build" 

[[redirects]]
  from = "/api/*"
  to = "https://<backend-url>/api/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
